name: NodeJS
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
            docker build nodejs --tag ghcr.io/knackstedt/gocd-agent-nodejs:latest
            docker push ghcr.io/knackstedt/gocd-agent-nodejs:latest
